import type { Project } from "../types/project";
export const PROJECTS: Project[] = [
export const PROJECTS = [
  {
    id: "p1",
    titleEn: "Luminous Loft",
    titleAr: "لوفت الضياء",
    titleTr: "Işıklı Loft",
    catEn: "Interior",
    catAr: "تصميم داخلي",
    catTr: "İç Mekan",
    scopeEn: "Small",
    scopeAr: "صغير",
    scopeTr: "Küçük",
    year: "2024",
    location: "Riyadh, KSA",
    scale: "180 sqm",
    roleEn: "Lead Architect",
    roleAr: "مهندس رئيسي",
    roleTr: "Baş Mimar",
    tools: ["Revit", "3ds Max", "V-Ray", "Adobe Photoshop"],
    img: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=1200",
    descEn: "Open-plan living where natural light dictates the spatial flow and material warmth.",
    descAr: "معيشة بمخطط مفتوح حيث يملي الضوء الطبيعي تدفق المساحة ودفء المواد.",
    descTr: "Doğal ışığın mekansal akışı ve malzeme sıcaklığını belirlediği açık plan yaşam.",
    story: {
      decisionEn: "Sacrificing an extra bedroom to create a continuous 'Light Corridor' that naturally illuminates the core of the apartment.",
      decisionAr: "التضحية بغرفة نوم إضافية لإنشاء 'ممر ضوء' متصل يضيء قلب الشقة بشكل طبيعي.",
      decisionTr: "Dairenin kalbini doğal olarak aydınlatan sürekli bir 'Işık Koridoru' oluşturmak için fazladan bir yatak odasından fedakarlık etmek.",
      challengeEn: "The original space felt confined and lacked natural light penetration, creating a gloomy atmosphere despite the large windows.",
      challengeAr: "كانت المساحة الأصلية تبدو ضيقة وتفتقر إلى تغلغل الضوء الطبيعي، مما خلق جواً كئيباً على الرغم من وجود نوافذ كبيرة.",
      challengeTr: "Orijinal mekan sıkışık hissettiriyordu ve büyük pencerelere rağmen doğal ışık nüfuzundan yoksundu, bu da kasvetli bir atmosfer yaratıyordu.",
      conceptEn: "We utilized a 'Light Corridor' concept, removing partitions and using reflective materials to bounce light deep into the space.",
      conceptAr: "استخدمنا مفهوم 'ممر الضوء'، حيث أزلنا القواطع واستخدمنا مواد عاكسة لتوجيه الضوء إلى عمق المكان.",
      conceptTr: "'Işık Koridoru' konseptini kullanarak bölmeleri kaldırdık ve ışığı mekanın derinliklerine yansıtmak için yansıtıcı malzemeler kullandık.",
      solutionEn: "By integrating open shelving and glass partitions, we maintained distinct zones without sacrificing the visual continuity.",
      solutionAr: "من خلال دمج الأرفف المفتوحة والقواطع الزجاجية، حافظنا على مناطق مميزة دون التضحية بالاستمرارية البصرية.",
      solutionTr: "Açık raflar ve cam bölmeleri entegre ederek, görsel süreklilikten ödün vermeden farklı bölgeleri koruduk.",
      reflectionEn: "This project taught me that natural light is a material in itself. Removing walls isn't just about space; it's about letting the sun paint the interior.",
      reflectionAr: "علمني هذا المشروع أن الضوء الطبيعي مادة بحد ذاتها. إزالة الجدران ليست مجرد توسعة للمكان، بل هي السماح للشمس برسم تفاصيل الداخل.",
      reflectionTr: "Bu proje bana doğal ışığın başlı başına bir malzeme olduğunu öğretti. Duvarları kaldırmak sadece mekanla ilgili değil; güneşin iç mekanı boyamasına izin vermekle ilgili."
    },
    reviews: [
      { id: "r1", userName: "Sarah Jenkins", rating: 5, text: "The way the light hits the floor in the morning is absolute poetry. A masterpiece of renovation.", createdAt: "2024-02-10" },
      { id: "r2", userName: "Ahmed Al-Farsi", rating: 4, text: "Excellent spatial planning, though I would have preferred warmer wood tones.", createdAt: "2024-03-05" }
    ],
    gallery: [
      "https://images.unsplash.com/photo-1600607686527-6fb886090705?q=80&w=1200",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=1200"
    ],
    process: [
      {
        type: "sketch",
        url: "https://images.unsplash.com/photo-1581094288338-2314dddb7ece?q=80&w=1200",
        captionEn: "Initial Zoning Sketches",
        captionAr: "سكتشات توزيع المناطق الأولية",
        captionTr: "İlk Bölgeleme Eskizleri"
      },
      {
        type: "diagram",
        url: "https://images.unsplash.com/photo-1634148967676-4dc5d774a382?q=80&w=1200",
        captionEn: "Light Circulation Diagram",
        captionAr: "مخطط حركة الضوء",
        captionTr: "Işık Sirkülasyon Şeması"
      }
    ],
    blueprints: [
      "https://images.unsplash.com/photo-1581094288338-2314dddb7ece?q=80&w=1200&auto=format&fit=crop"
    ],
    videoUrl: "",
    model3dUrl: "",
    presentationUrl: "#"
  },
  {
    id: "p2",
    titleEn: "Marble Sanctuary",
    titleAr: "ملاذ الرخام",
    titleTr: "Mermer Sığınak",
    catEn: "Decor",
    catAr: "ديكور",
    catTr: "Dekor",
    scopeEn: "Medium",
    scopeAr: "متوسط",
    scopeTr: "Orta",
    year: "2023",
    location: "Jeddah, KSA",
    scale: "450 sqm",
    roleEn: "Interior Designer",
    roleAr: "مصمم داخلي",
    roleTr: "İç Mimar",
    tools: ["SketchUp", "Lumion", "AutoCAD"],
    img: "https://images.unsplash.com/photo-1600607686527-6fb886090705?q=80&w=1200",
    descEn: "A study in textures, combining cold stone with soft textiles for balanced luxury.",
    descAr: "دراسة في الملامس، تجمع بين الحجر البارد والمنسوجات الناعمة لفخامة متوازنة.",
    descTr: "Dengeli bir lüks için soğuk taşı yumuşak tekstillerle birleştiren bir doku çalışması.",
    story: {
      decisionEn: "Integrating low-level ambient floor lighting to detach heavy stone walls from the floor, making them feel lighter and warmer.",
      decisionAr: "استخدام إضاءة أرضية خافتة لفصل الجدران الحجرية الثقيلة عن الأرض، مما يجعلها تبدو أخف وأكثر دفئاً.",
      decisionTr: "Ağır taş duvarları zeminden ayırmak, daha hafif ve sıcak hissettirmek için alçak seviyeli ambiyans zemin aydınlatmasını entegre etmek.",
      challengeEn: "Balancing the coldness of extensive marble usage with the need for a cozy, residential feel.",
      challengeAr: "الموازنة بين برودة استخدام الرخام المكثف والحاجة إلى شعور منزلي دافئ.",
      challengeTr: "Yoğun mermer kullanımının soğukluğu ile sıcak, konut hissi ihtiyacını dengelemek.",
      conceptEn: "Soft Brutalism - juxtaposition of raw stone textures with warm velvet and ambient lighting.",
      conceptAr: "الوحشية الناعمة - تباين ملمس الحجر الخام مع المخمل الدافئ والإضاءة المحيطة.",
      conceptTr: "Yumuşak Brütalizm - ham taş dokularının sıcak kadife ve ortam aydınlatmasıyla yan yana gelmesi.",
      solutionEn: "Custom joinery and integrated warm-temperature lighting softened the hard edges of the stone.",
      solutionAr: "النجارة المخصصة والإضاءة ذات الحرارة الدافئة خففت من حدة حواف الحجر.",
      solutionTr: "Özel doğramalar ve entegre sıcak sıcaklıkta aydınlatma, taşın sert kenarlarını yumuşattı.",
      reflectionEn: "I learned that luxury isn't about expensive materials, but about the 'temperature' of the space. Texture contrast creates the true feeling of home.",
      reflectionAr: "تعلمت أن الفخامة ليست في غلاء المواد، بل في 'درجة حرارة' المكان. تباين الملامس هو ما يخلق الشعور الحقيقي بالمنزل.",
      reflectionTr: "Lüksün pahalı malzemelerle değil, mekanın 'sıcaklığıyla' ilgili olduğunu öğrendim. Doku kontrastı gerçek ev hissini yaratır."
    },
    reviews: [
      { id: "r3", userName: "Marcus D.", rating: 5, text: "The texture contrast is phenomenal. It feels expensive yet inviting.", createdAt: "2023-11-15" }
    ],
    gallery: [
      "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=1200"
    ],
    process: [],
    blueprints: [],
    videoUrl: "",
    model3dUrl: "",
    presentationUrl: ""
  },
  {
    id: "p3",
    titleEn: "The Glass Villa",
    titleAr: "الفيلا الزجاجية",
    titleTr: "Cam Villa",
    catEn: "Architecture",
    catAr: "عمارة",
    catTr: "Mimari",
    scopeEn: "Large",
    scopeAr: "كبير",
    scopeTr: "Büyük",
    year: "2022",
    location: "Dubai, UAE",
    scale: "800 sqm",
    roleEn: "Design Architect",
    roleAr: "مهندس معماري",
    roleTr: "Tasarım Mimarı",
    tools: ["Rhino", "Grasshopper", "Twinmotion"],
    img: "https://images.unsplash.com/photo-1600596542815-3ad19fb812a7?q=80&w=1200",
    descEn: "Blurring the lines between indoor luxury and outdoor landscapes.",
    descAr: "طمس الخطوط الفاصلة بين الفخامة الداخلية والمناظر الطبيعية الخارجية.",
    descTr: "İç mekan lüksü ile dış peyzaj arasındaki çizgileri bulanıklaştırmak.",
    story: {
      decisionEn: "Implementing a dynamic kinetic louver system instead of solid walls to provide privacy without blocking the view.",
      decisionAr: "تنفيذ نظام كاسرات شمس ديناميكي متحرك بدلاً من الجدران الصلبة لتوفير الخصوصية دون حجب الإطلالة.",
      decisionTr: "Manzarayı engellemeden mahremiyet sağlamak için masif duvarlar yerine dinamik kinetik panjur sistemi uygulamak.",
      challengeEn: "Maximizing views while maintaining privacy in a dense neighborhood.",
      challengeAr: "تعظيم الإطلالات مع الحفاظ على الخصوصية في حي مكتظ.",
      challengeTr: "Yoğun bir mahallede mahremiyeti korurken manzarayı en üst düzeye çıkarmak.",
      conceptEn: "Inverted Courtyard - focusing the views inwards towards a private central oasis.",
      conceptAr: "الفناء المقلوب - تركيز الإطلالات نحو الداخل باتجاه واحة مركزية خاصة.",
      conceptTr: "Ters Avlu - manzarayı özel bir merkezi vahaya doğru içeriye odaklamak.",
      solutionEn: "Dynamic louvers system that adapts to the sun angle and privacy needs.",
      solutionAr: "نظام كاسرات شمس ديناميكي يتكيف مع زاوية الشمس واحتياجات الخصوصية.",
      solutionTr: "Güneş açısına ve mahremiyet ihtiyaçlarına uyum sağlayan dinamik panjur sistemi.",
      reflectionEn: "Technology in architecture should be invisible. The louvers work hard, but the resident only feels the comfort and privacy.",
      reflectionAr: "التكنولوجيا في العمارة يجب أن تكون غير مرئية. الكاسرات تعمل بجد، لكن الساكن يشعر فقط بالراحة والخصوصية.",
      reflectionTr: "Mimarlıkta teknoloji görünmez olmalıdır. Panjurlar çok çalışır, ancak sakinler sadece konforu ve mahremiyeti hisseder."
    },
    reviews: [
        { id: "r4", userName: "Dr. K. Al-Saud", rating: 5, text: "A futuristic vision. The privacy solutions are genius.", createdAt: "2022-08-20" },
        { id: "r5", userName: "Elena V.", rating: 5, text: "Stunning geometry.", createdAt: "2022-09-01" }
    ],
    gallery: [],
    process: [],
    blueprints: [],
    videoUrl: "",
    model3dUrl: "",
    presentationUrl: ""
  },
  {
    id: "p4",
    titleEn: "Zenith Workspace",
    titleAr: "مساحة عمل زينيث",
    titleTr: "Zenith Çalışma Alanı",
    catEn: "Interior",
    catAr: "تصميم داخلي",
    catTr: "İç Mekan",
    scopeEn: "Medium",
    scopeAr: "متوسط",
    scopeTr: "Orta",
    year: "2025",
    location: "Doha, Qatar",
    scale: "600 sqm",
    roleEn: "Project Manager",
    roleAr: "مدير مشروع",
    roleTr: "Proje Yöneticisi",
    tools: ["Revit", "Enscape"],
    img: "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1200",
    descEn: "A biophilic office design that increases productivity through connection with nature.",
    descAr: "تصميم مكتبي بيوفيلي يعزز الإنتاجية من خلال الاتصال بالطبيعة.",
    descTr: "Doğa ile bağlantı kurarak üretkenliği artıran biyofilik bir ofis tasarımı.",
    story: {
      decisionEn: "Replacing traditional cubicles with organic, curved 'pods' wrapped in acoustic felt and living greenery.",
      decisionAr: "استبدال المقصورات التقليدية بـ 'كبسولات' عضوية منحنية مغلفة باللباد الصوتي والنباتات الحية.",
      decisionTr: "Geleneksel kabinleri, akustik keçe ve canlı yeşilliklerle sarılmış organik, kavisli 'kozalarla' değiştirmek.",
      challengeEn: "The client wanted privacy for calls but insisted on a fully open collaboration culture.",
      challengeAr: "أراد العميل خصوصية للمكالمات لكنه أصر على ثقافة تعاون مفتوحة بالكامل.",
      challengeTr: "Müşteri, aramalar için gizlilik istedi ancak tamamen açık bir işbirliği kültüründe ısrar etti.",
      conceptEn: "The Forest Canopy - layers of density providing different levels of shelter.",
      conceptAr: "ظلة الغابة - طبقات من الكثافة توفر مستويات مختلفة من المأوى.",
      conceptTr: "Orman Gölgeliği - farklı barınma seviyeleri sağlayan yoğunluk katmanları.",
      solutionEn: "Used sound-absorbing moss walls as dividers and created specific 'quiet zones' marked by lower ceiling heights.",
      solutionAr: "استخدام جدران الطحالب الممتصة للصوت كفواصل وإنشاء 'مناطق هادئة' محددة بأسقف منخفضة.",
      solutionTr: "Bölücü olarak ses emici yosun duvarları kullanıldı ve daha alçak tavan yükseklikleri ile işaretlenmiş özel 'sessiz bölgeler' oluşturuldu.",
      reflectionEn: "Acoustics are the invisible architecture. If a space looks good but sounds bad, it fails.",
      reflectionAr: "الصوتيات هي العمارة غير المرئية. إذا كان المكان يبدو جيداً ولكن صوته سيء، فقد فشل.",
      reflectionTr: "Akustik görünmez mimaridir. Bir mekan iyi görünüyor ama sesi kötüyse, başarısız olur."
    },
    reviews: [
        { id: "r6", userName: "Tech Solutions CEO", rating: 5, text: "Our team loves coming to work now. The acoustics are perfect.", createdAt: "2025-01-15" }
    ],
    gallery: [
        "https://images.unsplash.com/photo-1497215728101-856f4ea42174?q=80&w=1200",
        "https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=1200"
    ],
    process: [],
    blueprints: [],
    videoUrl: "",
    model3dUrl: "",
    presentationUrl: ""
  },
  {
    id: "p5",
    titleEn: "Oasis Pavilion",
    titleAr: "جناح الواحة",
    titleTr: "Vaha Pavyonu",
    catEn: "Architecture",
    catAr: "عمارة",
    catTr: "Mimari",
    scopeEn: "Large",
    scopeAr: "كبير",
    scopeTr: "Büyük",
    year: "2023",
    location: "Al Ula, KSA",
    scale: "1200 sqm",
    roleEn: "Architect",
    roleAr: "مهندس معماري",
    roleTr: "Mimar",
    tools: ["Rhino", "Blender", "Unreal Engine"],
    img: "https://images.unsplash.com/photo-1511818966892-d7d671e672a2?q=80&w=1200",
    descEn: "A cultural center that merges seamlessly with the desert sandstone landscape.",
    descAr: "مركز ثقافي يندمج بسلاسة مع المناظر الطبيعية الصحراوية والحجر الرملي.",
    descTr: "Çöl kumtaşı manzarasıyla kusursuz bir şekilde birleşen bir kültür merkezi.",
    story: {
      decisionEn: "Using rammed earth construction technique sourced directly from the site's soil to minimize carbon footprint.",
      decisionAr: "استخدام تقنية البناء بالتربة المدكوكة المستخرجة مباشرة من تربة الموقع لتقليل البصمة الكربونية.",
      decisionTr: "Karbon ayak izini en aza indirmek için doğrudan sahadaki topraktan elde edilen sıkıştırılmış toprak inşaat tekniğinin kullanılması.",
      challengeEn: "Designing a structure that withstands harsh desert heat without relying heavily on HVAC.",
      challengeAr: "تصميم هيكل يتحمل حرارة الصحراء القاسية دون الاعتماد بشكل كبير على التكييف.",
      challengeTr: "HVAC sistemlerine aşırı güvenmeden sert çöl sıcağına dayanabilecek bir yapı tasarlamak.",
      conceptEn: "Erosion - Mimicking how wind carves stone over centuries.",
      conceptAr: "التعرية - محاكاة كيفية نحت الرياح للحجر عبر القرون.",
      conceptTr: "Erozyon - Rüzgarın yüzyıllar boyunca taşı nasıl oyduğunu taklit etmek.",
      solutionEn: "Thick thermal mass walls and wind towers (Barjeel) for passive cooling.",
      solutionAr: "جدران سميكة ذات كتلة حرارية وأبراج رياح (بارجيل) للتبريد السلبي.",
      solutionTr: "Pasif soğutma için kalın termal kütle duvarları ve rüzgar kuleleri (Barjeel).",
      reflectionEn: "True sustainability is looking back at ancient wisdom. The desert teaches us how to build if we listen.",
      reflectionAr: "الاستدامة الحقيقية هي النظر إلى الحكمة القديمة. الصحراء تعلمنا كيف نبني إذا استمعنا إليها.",
      reflectionTr: "Gerçek sürdürülebilirlik kadim bilgeliğe geri dönüp bakmaktır. Eğer dinlersek çöl bize nasıl inşa edileceğini öğretir."
    },
    reviews: [
        { id: "r7", userName: "Visitor 402", rating: 5, text: "It feels like it grew out of the ground. Breath-taking.", createdAt: "2023-12-01" },
        { id: "r8", userName: "Architectural Digest", rating: 5, text: "A triumph of contextual design.", createdAt: "2024-01-10" }
    ],
    gallery: [
        "https://images.unsplash.com/photo-1487958449943-2429e8be8625?q=80&w=1200"
    ],
    process: [],
    blueprints: [],
    videoUrl: "",
    model3dUrl: "",
    presentationUrl: ""
  }
];
